In [ ]:
import numpy as np
arr=np.array([10,20,40])
print(arr)

[10 20 40]

In [ ]:
print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)

dimension: 1
shape: (3,)
datatype: int64
size: 3

In [ ]:
print("item size of array:",arr.itemsize)

item size of array: 8

In [ ]:
print("dimension:",arr.ndim)
print("shape:",arr.shape)
print("datatype:",arr.dtype)
print("size:",arr.size)
print("item size of array:",arr.itemsize)
print("total size of array:",arr.nbytes)

dimension: 1
shape: (3,)
datatype: int64
size: 3
item size of array: 8
total size of array: 24

In [ ]:
import numpy as np
arr=np.array([10,20,40])
print(arr)

[10 20 40]

#1d advance indexing

In [ ]:
arr=np.array(np.arange(1,10))
print(arr)

[1 2 3 4 5 6 7 8 9]

In [ ]:
indices=[3,8]
arr[indices]

array([4, 9])

2d advance indexing

In [ ]:
 arr=np.array(np.linspace(1,100,20)).reshape(5,4)
 print(arr)

[[  1.           6.21052632  11.42105263  16.63157895]
 [ 21.84210526  27.05263158  32.26315789  37.47368421]
 [ 42.68421053  47.89473684  53.10526316  58.31578947]
 [ 63.52631579  68.73684211  73.94736842  79.15789474]
 [ 84.36842105  89.57894737  94.78947368 100.        ]]

In [ ]:
arr=np.array(np.linspace(1,100,20),dtype=int).reshape(5,4)
print(arr)

[[  1   6  11  16]
 [ 21  27  32  37]
 [ 42  47  53  58]
 [ 63  68  73  79]
 [ 84  89  94 100]]

In [ ]:
row=[0,2,4]
col=[3,1,3]

arr[row,col]

array([ 16,  47, 100])

3d advance slicing

In [ ]:
arr=np.array(np.linspace(1,100,24),dtype=int).reshape(3,2,4)
print(arr)

[[[  1   5   9  13]
  [ 18  22  26  31]]

 [[ 35  39  44  48]
  [ 52  56  61  65]]

 [[ 69  74  78  82]
  [ 87  91  95 100]]]

In [ ]:
cls=[0,1,2]
row=[1,1,1]
col=[1,3,1]
arr[cls,row,col]

array([22, 65, 91])

#filtering

In [ ]:
arr=np.array(np.linspace(1,99,16))
print(arr)

[ 1.          7.53333333 14.06666667 20.6        27.13333333 33.66666667
 40.2        46.73333333 53.26666667 59.8        66.33333333 72.86666667
 79.4        85.93333333 92.46666667 99.        ]

In [ ]:
arr=np.array(np.linspace(1,99,16),dtype=int)
print(arr)

[ 1  7 14 20 27 33 40 46 53 59 66 72 79 85 92 99]

In [ ]:
even_numbers=arr%2==0
even_numbers

array([False, False,  True,  True, False, False,  True,  True, False,
       False,  True,  True, False, False,  True, False])

In [ ]:
arr[even_numbers]

array([14, 20, 40, 46, 66, 72, 92])

In [ ]:
arr[arr%2!=0]

array([ 1,  7, 27, 33, 53, 59, 79, 85, 99])

##copy and view

In [ ]:
arr=np.array(np.arange(1,5))
print(arr)

[1 2 3 4]

In [ ]:
arr_1=arr.copy()
print(arr_1)

[1 2 3 4]

In [ ]:
arr_1[0]=100
print(arr_1)
print(arr)

[100   2   3   4]
[1 2 3 4]

In [ ]:
print(np.shares_memory(arr,arr_1))

False

In [ ]:
arr=np.array(np.arange(1,5))
print(arr)
arr_2=arr.view()
print(arr_2)
print(np.shares_memory(arr,arr_2))

[1 2 3 4]
[1 2 3 4]
True

In [ ]:
arr_2[0]=99

In [ ]:
import numpy as np
maths = np.array([56,74,83,92,65])
science = np.array([70,86,87,95,65])
print("maths marks:",maths)
print("science marks:",science)
print("\n1. ADD")
total=np.add(maths,science)
print(total)

maths marks: [56 74 83 92 65]
science marks: [70 86 87 95 65]

1. ADD
[126 160 170 187 130]

In [ ]:
print("\n2.SUBTRACT")
difference=np.subtract(maths,science)
print(difference)

2.SUBTRACT
[-14 -12  -4  -3   0]

In [ ]:
print("\n3.MULTIPLY")
product=np.multiply(maths,science)
print(product)

3.MULTIPLY
[3920 6364 7221 8740 4225]

In [ ]:
print("\n4.DIVIDE")
division=np.divide(maths,science)
print(division)

4.DIVIDE
[0.8        0.86046512 0.95402299 0.96842105 1.        ]

#Floor divide

In [ ]:
print("\n5.FLOOR DIVIDE")
floor_division=np.floor_divide(maths,science)
print(floor_division)

5.FLOOR DIVIDE
[0 0 0 0 1]

#Power

In [ ]:
numbers=np.array([2,3,4,5])
print("\n6.POWER")
print(numbers)
result=np.power(numbers,2)
print(result)

6.POWER
[2 3 4 5]
[ 4  9 16 25]

#Mod

In [ ]:
numbers=np.array([10,15,22,54,30])
print("\n7.MOD")
print(np.mod(numbers,4))

7.MOD
[2 3 2 2 2]

#reminder

In [ ]:
print("\n8.REMAINDER")
print(np.remainder(numbers,4))

8.REMAINDER
[2 3 2 2 2]

#negetive

In [ ]:
profit=np.array([5000,3000,7000,4500])
print("\n10.NEGATIVE")
print(profit)
print(np.negative(profit))

10.NEGATIVE
[5000 3000 7000 4500]
[-5000 -3000 -7000 -4500]

#abs

In [ ]:
temperature=np.array([-10,-5,9,-20,15])
print("\n11.ABS")
print(temperature)
print(np.abs(temperature))

11.ABS
[-10  -5   9 -20  15]
[10  5  9 20 15]

#count nonzero

In [ ]:
attendence=np.array([1,1,0,1,1,0,1,1,1,0])
print("\n1.COUNT_NONZERO")
print("attendence:",attendence)
print("present students:",np.count_nonzero(attendence))
print("absent students:",np.count_nonzero(attendence))

1.COUNT_NONZERO
attendence: [1 1 0 1 1 0 1 1 1 0]
present students: 7
absent students: 7

#unique

In [ ]:
marks=[10,20,30,40,50,60]
print("\n2.UNIQUE")
print(np.unique(marks))

2.UNIQUE
[10 20 30 40 50 60]

#bincount

In [ ]:
ratings=np.array([5,4,5,3,2,5,4,5,6,3,2])
print("\n3.BINCOUNT")
print("ratings:",ratings)
print(np.bincount(ratings))

3.BINCOUNT
ratings: [5 4 5 3 2 5 4 5 6 3 2]
[0 0 2 2 2 4 1]

#SUM

In [ ]:
marks=[10,20,30,40,50,60]
print("\n4.SUM")
print("total marks:",np.sum(marks))

4.SUM
total marks: 210

#CUMSUM

In [ ]:
marks=[10,20,30,40,50,60]
print("\n5.CUMSUM")
print(np.cumsum(marks))

5.CUMSUM
[ 10  30  60 100 150 210]

#prod

In [ ]:
numbers=np.array([2,3,4,5])
print("\n6.PROD")
print(numbers)
print(np.prod(numbers))

6.PROD
[2 3 4 5]
120

#cumprod

In [ ]:
print("\n7.CUMPROD")
print(numbers)
print(np.cumprod(numbers))

7.CUMPROD
[2 3 4 5]
[  2   6  24 120]

In [ ]:
arr=np.array(np.arange(1,11),dtype=int)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]

In [ ]:
sumofarr=arr.sum()
print("total number of elemnts:",arr.size)
print("total sum of array:",sumofarr)
mean=arr.mean()
print("mean of the array:",mean)

total number of elemnts: 10
total sum of array: 55
mean of the array: 5.5

In [ ]:
 marks = np.array([10,20,30,40,50,60])
 print("\n2.MEDIAN")
 print(np.median(marks))

2.MEDIAN
35.0

In [ ]:
print("\n3.VARIANCE")
print(np.var(marks))

3.VARIANCE
291.6666666666667

In [ ]:
print("\n4.STANDARD DEVIATION")
print(np.std(marks))

4.STANDARD DEVIATION
17.07825127659933

In [ ]:
print("\n5.MAXIMUM")
print(np.max(marks))

5.MAXIMUM
60

In [ ]:
print("\n6.MINIMUM")
print(np.min(marks))

6.MINIMUM
10

In [ ]:
name="Arati"
for index,value in enumerate(name):
  print(index,"=====",value)

0 ===== A
1 ===== r
2 ===== a
3 ===== t
4 ===== i

In [ ]:
name="Rutika chougale"
for index,value in enumerate(name):
  if(value==" "):
     print(index,"=====",name[index+1])

6 ===== c

In [ ]:
arr=np.array(np.arange(1,10))
for index,value in enumerate(arr):
    print(index,"=====",value)

0 ===== 1
1 ===== 2
2 ===== 3
3 ===== 4
4 ===== 5
5 ===== 6
6 ===== 7
7 ===== 8
8 ===== 9

In [ ]:
arr=np.array(np.arange(1,13)).reshape(3,4)
print(arr)
print()
for index,value in enumerate(arr):
    print(index,"=====",value)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

0 ===== [1 2 3 4]
1 ===== [5 6 7 8]
2 ===== [ 9 10 11 12]

In [ ]:
arr=np.array(np.arange(1,13)).reshape(3,4)
print(arr)
print()
for index,value in np.ndenumerate(arr):
    print(index,"=====",value)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

(0, 0) ===== 1
(0, 1) ===== 2
(0, 2) ===== 3
(0, 3) ===== 4
(1, 0) ===== 5
(1, 1) ===== 6
(1, 2) ===== 7
(1, 3) ===== 8
(2, 0) ===== 9
(2, 1) ===== 10
(2, 2) ===== 11
(2, 3) ===== 12

In [ ]:
import numpy as np
a=np.arange(2*3).reshape(2,3)
print(a)
it = np.nditer(a)
for i in it:
  print(i)

[[0 1 2]
 [3 4 5]]
0
1
2
3
4
5

#flatten() vs ravel()

In [ ]:
arr=np.array(np.arange(1,22)).reshape(3,7)
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]

In [ ]:
b=arr.flatten()
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]

In [ ]:
b[0]=100
print(arr)
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21]

In [ ]:
b=arr.ravel()
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]

#SORTING

In [ ]:
arr=np.array(np.linspace(-100,100,20),dtype=int)
print(arr)

[-100  -89  -78  -68  -57  -47  -36  -26  -15   -5    5   15   26   36
   47   57   68   78   89  100]

In [ ]:
arr=np.sort(arr)
print(arr)

[-100  -89  -78  -68  -57  -47  -36  -26  -15   -5    5   15   26   36
   47   57   68   78   89  100]

In [ ]:
arr=np.sort(arr)[::-1]
print(arr)

[ 100   89   78   68   57   47   36   26   15    5   -5  -15  -26  -36
  -47  -57  -68  -78  -89 -100]

In [ ]:
arr=np.array(np.arange(0,21),dtype=int).reshape(7,3)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]

In [ ]:
arr=np.sort(arr)

In [ ]:
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]

In [ ]:
arr=np.sort(arr,axis=1)
print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]

In [ ]:
arr=np.array([[1,11,32,2],[3,0,44,77],[1,2,5,6]])
print(arr)

[[ 1 11 32  2]
 [ 3  0 44 77]
 [ 1  2  5  6]]

In [ ]:
arr=np.sort(arr)
print(arr)

[[ 1  2 11 32]
 [ 0  3 44 77]
 [ 1  2  5  6]]

In [ ]:
arr=np.sort(arr,axis=1)
print(arr)

[[ 1  2 11 32]
 [ 0  3 44 77]
 [ 1  2  5  6]]

#pandas

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
ser=pd.Series(["kle","srm","vit"])
print(ser)

0    kle
1    srm
2    vit
dtype: object

In [ ]:
import pandas as pd
ser=pd.Series(["kle","srm","vit"],index=["college-1","college-2","college-3"])
print(ser)

college-1    kle
college-2    srm
college-3    vit
dtype: object

In [ ]:
import pandas as pd
ser=pd.Series(["kle","srm","vit"])
print(ser)
print(type(ser))

0    kle
1    srm
2    vit
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
import pandas as pd
import numpy as np
ser=pd.Series(["kle","srm","vit"])
print(ser)
print(type(ser))
print("==========================")
print("dimennsions:",ser.ndim)
print("shape:",ser.shape)

0    kle
1    srm
2    vit
dtype: object
<class 'pandas.core.series.Series'>
==========================
dimennsions: 1
shape: (3,)

In [ ]:
import pandas as pd
import  numpy as np
ser=pd.Series([100, 200 ,300],index=["college-1","college-2","college-3"])
print(ser)

college-1    100
college-2    200
college-3    300
dtype: int64

In [ ]:
print(ser.iloc[0])
print(ser.iloc[1])
print(ser.iloc[2])

100
200
300

In [ ]:
print(ser.loc["college-1"])
print(ser.loc["college-2"])
print(ser.loc["college-3"])

100
200
300

In [ ]:
import pandas as pd
students=pd.Series([85,92,78,96,88,74,90],
                   index=["student-1","student-2","student-3","student-4","student-5","student-6","student-7"])
print(students)

student-1    85
student-2    92
student-3    78
student-4    96
student-5    88
student-6    74
student-7    90
dtype: int64

In [ ]:
students.loc["student-7"]

np.int64(90)

In [ ]:
students.iloc[-1]

np.int64(90)

In [ ]:
import numpy as np
first_number=int(input("enter your number:"))
second_number=int(input("enter your number:"))
sum=np.add(first_number,second_number)
print(sum)

enter your number:10
enter your number:20
30

In [ ]:
import pandas as pd
students=pd.Series([85,92,78,96,88,74,90],
                   index=["student-1","student-2","student-3","student-4","student-5","student-6","student-7"])
print(students)

student-1    85
student-2    92
student-3    78
student-4    96
student-5    88
student-6    74
student-7    90
dtype: int64

In [ ]:
students.loc["student-1":"student-7"]

student-1    85
student-2    92
student-3    78
student-4    96
student-5    88
student-6    74
student-7    90
dtype: int64

In [ ]:
students.iloc[0:6]

student-1    85
student-2    92
student-3    78
student-4    96
student-5    88
student-6    74
dtype: int64

In [ ]:
students.iloc[0:6:3]

student-1    85
student-4    96
dtype: int64

In [ ]:
students.loc["student-1":"student-7":2]

student-1    85
student-3    78
student-5    88
student-7    90
dtype: int64

In [ ]:
names=pd.Series(["shiva","praveen","anjali","sujji"],index=["student-1","student-2","student-3","student-4"])
print(names)

student-1      shiva
student-2    praveen
student-3     anjali
student-4      sujji
dtype: object

In [ ]:
names["student-1"]="arati"

In [ ]:
print(names)

student-1      arati
student-2    praveen
student-3     anjali
student-4      sujji
dtype: object

In [ ]:
names[1]="rajaa"

/tmp/ipykernel_2073/2398984722.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  names[1]="rajaa"

In [ ]:
print(names)

student-1     arati
student-2     rajaa
student-3    anjali
student-4     sujji
dtype: object

In [ ]:
names[1:4]=["rutika","cr-1","cr-2"]

In [ ]:
print(names)

student-1     arati
student-2    rutika
student-3      cr-1
student-4      cr-2
dtype: object

In [ ]:
indices=[1,3]
names[indices]=["hi","bye"]
print(names)

student-1    arati
student-2       hi
student-3     cr-1
student-4      bye
dtype: object

/tmp/ipykernel_2073/3608861859.py:2: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  names[indices]=["hi","bye"]

In [ ]:

names[[1,3]]=["hi","bye"]
print(names)

student-1    arati
student-2       hi
student-3     cr-1
student-4      bye
dtype: object

/tmp/ipykernel_2073/472526945.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  names[[1,3]]=["hi","bye"]

In [ ]:
import numpy as np
arr=np.array([5,10,15,20,25])
print(arr)

[ 5 10 15 20 25]

In [ ]:
arr=np.array(np.arange(0,9)).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]