In [ ]:
import pandas as pd
arr=pd.Series([10,20,30,40],name="marks")
print(arr)

0    10
1    20
2    30
3    40
Name: marks, dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
arr=pd.Series([10,20,30,40],index=["english","c","python","java"],name="marks")
print(arr)

english    10
c          20
python     30
java       40
Name: marks, dtype: int64

In [ ]:
print(arr.loc["c"])

20

In [ ]:
print(arr.iloc[1])

20

In [ ]:
print(arr.loc["c":"java"])

c         20
python    30
java      40
Name: marks, dtype: int64

In [ ]:
arr[0]=500
print(arr)

english    500
c           20
python      30
java        40
Name: marks, dtype: int64

/tmp/ipykernel_1937/1731888521.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  arr[0]=500

In [ ]:
arr[0:3]=100

In [ ]:
print(arr)

english    100
c          100
python     100
java        40
Name: marks, dtype: int64

In [ ]:
df=pd.DataFrame([[1,2,3],[4,5,6]])
print(df)

   0  1  2
0  1  2  3
1  4  5  6

In [ ]:
df=pd.DataFrame([[1,2,3],[4,5,6]],index=["boys","girls"],columns=["english","c","python"])
print(df)

       english  c  python
boys         1  2       3
girls        4  5       6

In [ ]:
df=pd.DataFrame({"english":[10,20,30,40],"c":[100,200,300,400],"python":[1000,2000,3000,4000]},index=["cls-1","cls-2","cls-3","cls-4"])
print(df)

       english    c  python
cls-1       10  100    1000
cls-2       20  200    2000
cls-3       30  300    3000
cls-4       40  400    4000

In [ ]:
df["english"]

cls-1    10
cls-2    20
cls-3    30
cls-4    40
Name: english, dtype: int64

In [ ]:
df.loc["cls-1"]

english      10
c           100
python     1000
Name: cls-1, dtype: int64

In [ ]:
df=pd.DataFrame({"english":[10,20,30,40],"c":[100,200,300,400],"python":[1000,2000,3000,4000]},index=["cls-1","cls-2","cls-3","cls-4"])
print(df)

       english    c  python
cls-1       10  100    1000
cls-2       20  200    2000
cls-3       30  300    3000
cls-4       40  400    4000

In [ ]:
print(df.index)

Index(['cls-1', 'cls-2', 'cls-3', 'cls-4'], dtype='object')

In [ ]:
print(df.columns)

Index(['english', 'c', 'python'], dtype='object')

In [ ]:
print(df.axes)

[Index(['cls-1', 'cls-2', 'cls-3', 'cls-4'], dtype='object'), Index(['english', 'c', 'python'], dtype='object')]

In [ ]:
print(df.dtypes)

english    int64
c          int64
python     int64
dtype: object

In [ ]:
print(df.shape)

(4, 3)

In [ ]:
print(df.size)

12

In [ ]:
print(df.ndim)

2

In [ ]:
print(df.empty)

False

In [ ]:
print(df.values)

[[  10  100 1000]
 [  20  200 2000]
 [  30  300 3000]
 [  40  400 4000]]

In [ ]:
df

       english    c  python
cls-1       10  100    1000
cls-2       20  200    2000
cls-3       30  300    3000
cls-4       40  400    4000

In [ ]:
print(df.T)

         cls-1  cls-2  cls-3  cls-4
english     10     20     30     40
c          100    200    300    400
python    1000   2000   3000   4000

In [ ]:
df_1=pd.DataFrame()
print(df_1.empty)

True

In [ ]:
df.head(2)

       english    c  python
cls-1       10  100    1000
cls-2       20  200    2000

In [ ]:
df.tail(2)

       english    c  python
cls-3       30  300    3000
cls-4       40  400    4000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, cls-1 to cls-4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   english  4 non-null      int64
 1   c        4 non-null      int64
 2   python   4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes

In [ ]:
df.describe()

         english           c       python
count   4.000000    4.000000     4.000000
mean   25.000000  250.000000  2500.000000
std    12.909944  129.099445  1290.994449
min    10.000000  100.000000  1000.000000
25%    17.500000  175.000000  1750.000000
50%    25.000000  250.000000  2500.000000
75%    32.500000  325.000000  3250.000000
max    40.000000  400.000000  4000.000000

In [ ]:
df.count()

english    4
c          4
python     4
dtype: int64

In [ ]:
df.size

12

In [ ]:
df.sample()

       english    c  python
cls-2       20  200    2000

In [ ]:
a=pd.Series([10,20,30,40])
b=pd.Series([20,30,None])
print(a)

print("================")

print(b)


print("================")

print(a+b)

0    10
1    20
2    30
3    40
dtype: int64
================
0    20.0
1    30.0
2     NaN
dtype: float64
================
0    30.0
1    50.0
2     NaN
3     NaN
dtype: float64

In [ ]:
c=a+b
print(c)

0    30.0
1    50.0
2     NaN
3     NaN
dtype: float64

In [ ]:
c=a.add(b,fill_value=0)
print(c)

0    30.0
1    50.0
2    30.0
3    40.0
dtype: float64

In [ ]:
c=a-b
print(c)

0   -10.0
1   -10.0
2     NaN
3     NaN
dtype: float64

In [ ]:
c=a.sub(b,fill_value=0)
print(c)

0   -10.0
1   -10.0
2    30.0
3    40.0
dtype: float64

In [ ]:
import pandas as pd
df1=pd.DataFrame({"name":["ram","sam"],"age":[20,21]})
df2=pd.DataFrame({"name":["arati","rutika"],"age":[22,23]})
result=pd.concat([df1,df2])
print(result)

     name  age
0     ram   20
1     sam   21
0   arati   22
1  rutika   23

In [ ]:
import pandas as pd
df1=pd.DataFrame({"name":["ram","sam"],"age":[20,21]})
df2=pd.DataFrame({"name":["arati","rutika"],"age":[22,23]})
result=pd.concat([df1,df2],ignore_index=True)
print(result)

     name  age
0     ram   20
1     sam   21
2   arati   22
3  rutika   23

In [ ]:
df.head(1)

       english    c  python
cls-1       10  100    1000

In [ ]:
df=pd.read_csv("/content/std.csv",header=None)
print(df)

                                                    0
0   | Roll No | Name           | Age | Gender | Cl...
1   | ------: | -------------- | --: | ------ | --...
2   |       1 | Aarav Sharma   |  15 | Male   | 10...
3   |       2 | Ananya Patel   |  15 | Female | 10...
4   |       3 | Rohan Gupta    |  16 | Male   | 10...
5   |       4 | Priya Singh    |  15 | Female | 10...
6   |       5 | Arjun Kumar    |  15 | Male   | 10...
7   |       6 | Sneha Verma    |  16 | Female | 10...
8   |       7 | Rahul Joshi    |  15 | Male   | 10...
9   |       8 | Neha Reddy     |  15 | Female | 10...
10  |       9 | Karan Mehta    |  16 | Male   | 10...
11  |      10 | Pooja Nair     |  15 | Female | 10...
12  |      11 | Aditya Rao     |  15 | Male   | 10...
13  |      12 | Isha Kapoor    |  16 | Female | 10...
14  |      13 | Vivek Das      |  15 | Male   | 10...
15  |      14 | Kavya Iyer     |  15 | Female | 10...
16  |      15 | Manish Yadav   |  16 | Male   | 10...
17  |      16 | Divya Mishra   |  15 | Female | 10...
18  |      17 | Nikhil Jain    |  15 | Male   | 10...
19  |      18 | Aditi Chawla   |  16 | Female | 10...
20  |      19 | Harsh Agarwal  |  15 | Male   | 10...
21  |      20 | Simran Kaur    |  15 | Female | 10...
22  |      21 | Yash Malhotra  |  16 | Male   | 10...
23  |      22 | Meera Pillai   |  15 | Female | 10...
24  |      23 | Siddharth Roy  |  15 | Male   | 10...
25  |      24 | Riya Shah      |  16 | Female | 10...
26  |      25 | Akash Bhat     |  15 | Male   | 10...
27  |      26 | Nandini Ghosh  |  15 | Female | 10...
28  |      27 | Deepak Soni    |  16 | Male   | 10...
29  |      28 | Tanvi Kulkarni |  15 | Female | 10...
30  |      29 | Mohit Arora    |  15 | Male   | 10...
31  |      30 | Ritika Sen     |  16 | Female | 10...
32  |      31 | Aryan Saxena   |  15 | Male   | 10...
33  |      32 | Shreya Bose    |  15 | Female | 10...
34  |      33 | Varun Menon    |  16 | Male   | 10...
35  |      34 | Muskan Arora   |  15 | Female | 10...
36  |      35 | Gaurav Pandey  |  15 | Male   | 10...
37  |      36 | Ishita Dutta   |  16 | Female | 10...
38  |      37 | Rohit Kulkarni |  15 | Male   | 10...
39  |      38 | Sanjana Rao    |  15 | Female | 10...
40  |      39 | Aman Tiwari    |  16 | Male   | 10...
41  |      40 | Bhavana Shetty |  15 | Female | 10...
42  |      41 | Chirag Desai   |  15 | Male   | 10...
43  |      42 | Aishwarya Naik |  16 | Female | 10...
44  |      43 | Kunal Bansal   |  15 | Male   | 10...
45  |      44 | Diya Kapoor    |  15 | Female | 10...
46  |      45 | Sahil Khanna   |  16 | Male   | 10...
47  |      46 | Nikita Sharma  |  15 | Female | 10...
48  |      47 | Pranav Nanda   |  15 | Male   | 10...
49  |      48 | Radhika Joshi  |  16 | Female | 10...
50  |      49 | Dev Malviya    |  15 | Male   | 10...
51  |      50 | Shruti Patil   |  15 | Female | 10...

In [ ]:
df=pd.read_excel("/content/std2.xlsx")
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Roll No,Name,Age,Gender,Class,Section,Math,Science,English,Total
1,1,Aarav Sharma,15,Male,10,A,85,88,90,263
2,2,Ananya Patel,15,Female,10,A,92,95,91,278
3,3,Rohan Gupta,16,Male,10,A,78,80,82,240
4,4,Priya Singh,15,Female,10,A,89,87,93,269
5,5,Arjun Kumar,15,Male,10,A,76,79,75,230
6,6,Sneha Verma,16,Female,10,A,94,91,95,280
7,7,Rahul Joshi,15,Male,10,A,68,72,70,210
8,8,Neha Reddy,15,Female,10,A,81,84,86,251
9,9,Karan Mehta,16,Male,10,A,88,85,87,260
10,10,Pooja Nair,15,Female,10,A,90,89,92,271
11,11,Aditya Rao,15,Male,10,B,73,77,74,224
12,12,Isha Kapoor,16,Female,10,B,95,96,94,285
13,13,Vivek Das,15,Male,10,B,84,82,80,246
14,14,Kavya Iyer,15,Female,10,B,91,90,89,270
15,15,Manish Yadav,16,Male,10,B,69,71,68,208
16,16,Divya Mishra,15,Female,10,B,87,89,90,266
17,17,Nikhil Jain,15,Male,10,B,79,81,83,243
18,18,Aditi Chawla,16,Female,10,B,93,94,92,279
19,19,Harsh Agarwal,15,Male,10,B,75,78,77,230
20,20,Simran Kaur,15,Female,10,B,86,88,85,259
21,21,Yash Malhotra,16,Male,10,C,82,84,81,247
22,22,Meera Pillai,15,Female,10,C,96,97,98,291
23,23,Siddharth Roy,15,Male,10,C,71,73,75,219
24,24,Riya Shah,16,Female,10,C,88,90,91,269
25,25,Akash Bhat,15,Male,10,C,80,78,79,237
26,26,Nandini Ghosh,15,Female,10,C,89,91,90,270
27,27,Deepak Soni,16,Male,10,C,74,76,72,222
28,28,Tanvi Kulkarni,15,Female,10,C,92,93,94,279
29,29,Mohit Arora,15,Male,10,C,83,81,82,246
30,30,Ritika Sen,16,Female,10,C,90,88,89,267
31,31,Aryan Saxena,15,Male,10,D,77,79,80,236
32,32,Shreya Bose,15,Female,10,D,94,95,96,285
33,33,Varun Menon,16,Male,10,D,81,83,82,246
34,34,Muskan Arora,15,Female,10,D,87,86,88,261
35,35,Gaurav Pandey,15,Male,10,D,72,74,73,219
36,36,Ishita Dutta,16,Female,10,D,91,92,90,273
37,37,Rohit Kulkarni,15,Male,10,D,84,82,85,251
38,38,Sanjana Rao,15,Female,10,D,95,94,93,282
39,39,Aman Tiwari,16,Male,10,D,78,80,79,237
40,40,Bhavana Shetty,15,Female,10,D,88,89,87,264
41,41,Chirag Desai,15,Male,10,E,85,84,86,255
42,42,Aishwarya Naik,16,Female,10,E,97,96,95,288
43,43,Kunal Bansal,15,Male,10,E,76,78,77,231
44,44,Diya Kapoor,15,Female,10,E,89,91,92,272
45,45,Sahil Khanna,16,Male,10,E,80,81,82,243
46,46,Nikita Sharma,15,Female,10,E,93,92,94,279
47,47,Pranav Nanda,15,Male,10,E,70,72,71,213
48,48,Radhika Joshi,16,Female,10,E,90,89,91,270
49,49,Dev Malviya,15,Male,10,E,82,83,84,249
50,50,Shruti Patil,15,Female,10,E,95,94,96,285

In [ ]:
print(df.index)

RangeIndex(start=0, stop=51, step=1)

In [ ]:
print(df.columns)

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [ ]:
print(df.axes)

[RangeIndex(start=0, stop=51, step=1), Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')]

In [ ]:
print(df.dtypes)

Unnamed: 0    object
Unnamed: 1    object
Unnamed: 2    object
Unnamed: 3    object
Unnamed: 4    object
Unnamed: 5    object
Unnamed: 6    object
Unnamed: 7    object
Unnamed: 8    object
Unnamed: 9    object
dtype: object

In [ ]:
print(df.size)

510

In [ ]:
print(df.shape)

(51, 10)

In [ ]:
print(df.ndim)

2

In [ ]:
print(df.empty)

False

In [ ]:
print(df.T)

                 0             1             2            3            4   \
Unnamed: 0  Roll No             1             2            3            4
Unnamed: 1     Name  Aarav Sharma  Ananya Patel  Rohan Gupta  Priya Singh
Unnamed: 2      Age            15            15           16           15
Unnamed: 3   Gender          Male        Female         Male       Female
Unnamed: 4    Class            10            10           10           10
Unnamed: 5  Section             A             A            A            A
Unnamed: 6     Math            85            92           78           89
Unnamed: 7  Science            88            95           80           87
Unnamed: 8  English            90            91           82           93
Unnamed: 9    Total           263           278          240          269

                     5            6            7           8            9   \
Unnamed: 0            5            6            7           8            9
Unnamed: 1  Arjun Kumar  Sneha Verma  Rahul Joshi  Neha Reddy  Karan Mehta
Unnamed: 2           15           16           15          15           16
Unnamed: 3         Male       Female         Male      Female         Male
Unnamed: 4           10           10           10          10           10
Unnamed: 5            A            A            A           A            A
Unnamed: 6           76           94           68          81           88
Unnamed: 7           79           91           72          84           85
Unnamed: 8           75           95           70          86           87
Unnamed: 9          230          280          210         251          260

            ...            41              42            43           44  \
Unnamed: 0  ...            41              42            43           44
Unnamed: 1  ...  Chirag Desai  Aishwarya Naik  Kunal Bansal  Diya Kapoor
Unnamed: 2  ...            15              16            15           15
Unnamed: 3  ...          Male          Female          Male       Female
Unnamed: 4  ...            10              10            10           10
Unnamed: 5  ...             E               E             E            E
Unnamed: 6  ...            85              97            76           89
Unnamed: 7  ...            84              96            78           91
Unnamed: 8  ...            86              95            77           92
Unnamed: 9  ...           255             288           231          272

                      45             46            47             48  \
Unnamed: 0            45             46            47             48
Unnamed: 1  Sahil Khanna  Nikita Sharma  Pranav Nanda  Radhika Joshi
Unnamed: 2            16             15            15             16
Unnamed: 3          Male         Female          Male         Female
Unnamed: 4            10             10            10             10
Unnamed: 5             E              E             E              E
Unnamed: 6            80             93            70             90
Unnamed: 7            81             92            72             89
Unnamed: 8            82             94            71             91
Unnamed: 9           243            279           213            270

                     49            50
Unnamed: 0           49            50
Unnamed: 1  Dev Malviya  Shruti Patil
Unnamed: 2           15            15
Unnamed: 3         Male        Female
Unnamed: 4           10            10
Unnamed: 5            E             E
Unnamed: 6           82            95
Unnamed: 7           83            94
Unnamed: 8           84            96
Unnamed: 9          249           285

[10 rows x 51 columns]

In [ ]:
print(df.values)

[['Roll No' 'Name' 'Age' 'Gender' 'Class' 'Section' 'Math' 'Science'
  'English' 'Total']
 [1 'Aarav Sharma' 15 'Male' 10 'A' 85 88 90 263]
 [2 'Ananya Patel' 15 'Female' 10 'A' 92 95 91 278]
 [3 'Rohan Gupta' 16 'Male' 10 'A' 78 80 82 240]
 [4 'Priya Singh' 15 'Female' 10 'A' 89 87 93 269]
 [5 'Arjun Kumar' 15 'Male' 10 'A' 76 79 75 230]
 [6 'Sneha Verma' 16 'Female' 10 'A' 94 91 95 280]
 [7 'Rahul Joshi' 15 'Male' 10 'A' 68 72 70 210]
 [8 'Neha Reddy' 15 'Female' 10 'A' 81 84 86 251]
 [9 'Karan Mehta' 16 'Male' 10 'A' 88 85 87 260]
 [10 'Pooja Nair' 15 'Female' 10 'A' 90 89 92 271]
 [11 'Aditya Rao' 15 'Male' 10 'B' 73 77 74 224]
 [12 'Isha Kapoor' 16 'Female' 10 'B' 95 96 94 285]
 [13 'Vivek Das' 15 'Male' 10 'B' 84 82 80 246]
 [14 'Kavya Iyer' 15 'Female' 10 'B' 91 90 89 270]
 [15 'Manish Yadav' 16 'Male' 10 'B' 69 71 68 208]
 [16 'Divya Mishra' 15 'Female' 10 'B' 87 89 90 266]
 [17 'Nikhil Jain' 15 'Male' 10 'B' 79 81 83 243]
 [18 'Aditi Chawla' 16 'Female' 10 'B' 93 94 92 279]
 [19 'Harsh Agarwal' 15 'Male' 10 'B' 75 78 77 230]
 [20 'Simran Kaur' 15 'Female' 10 'B' 86 88 85 259]
 [21 'Yash Malhotra' 16 'Male' 10 'C' 82 84 81 247]
 [22 'Meera Pillai' 15 'Female' 10 'C' 96 97 98 291]
 [23 'Siddharth Roy' 15 'Male' 10 'C' 71 73 75 219]
 [24 'Riya Shah' 16 'Female' 10 'C' 88 90 91 269]
 [25 'Akash Bhat' 15 'Male' 10 'C' 80 78 79 237]
 [26 'Nandini Ghosh' 15 'Female' 10 'C' 89 91 90 270]
 [27 'Deepak Soni' 16 'Male' 10 'C' 74 76 72 222]
 [28 'Tanvi Kulkarni' 15 'Female' 10 'C' 92 93 94 279]
 [29 'Mohit Arora' 15 'Male' 10 'C' 83 81 82 246]
 [30 'Ritika Sen' 16 'Female' 10 'C' 90 88 89 267]
 [31 'Aryan Saxena' 15 'Male' 10 'D' 77 79 80 236]
 [32 'Shreya Bose' 15 'Female' 10 'D' 94 95 96 285]
 [33 'Varun Menon' 16 'Male' 10 'D' 81 83 82 246]
 [34 'Muskan Arora' 15 'Female' 10 'D' 87 86 88 261]
 [35 'Gaurav Pandey' 15 'Male' 10 'D' 72 74 73 219]
 [36 'Ishita Dutta' 16 'Female' 10 'D' 91 92 90 273]
 [37 'Rohit Kulkarni' 15 'Male' 10 'D' 84 82 85 251]
 [38 'Sanjana Rao' 15 'Female' 10 'D' 95 94 93 282]
 [39 'Aman Tiwari' 16 'Male' 10 'D' 78 80 79 237]
 [40 'Bhavana Shetty' 15 'Female' 10 'D' 88 89 87 264]
 [41 'Chirag Desai' 15 'Male' 10 'E' 85 84 86 255]
 [42 'Aishwarya Naik' 16 'Female' 10 'E' 97 96 95 288]
 [43 'Kunal Bansal' 15 'Male' 10 'E' 76 78 77 231]
 [44 'Diya Kapoor' 15 'Female' 10 'E' 89 91 92 272]
 [45 'Sahil Khanna' 16 'Male' 10 'E' 80 81 82 243]
 [46 'Nikita Sharma' 15 'Female' 10 'E' 93 92 94 279]
 [47 'Pranav Nanda' 15 'Male' 10 'E' 70 72 71 213]
 [48 'Radhika Joshi' 16 'Female' 10 'E' 90 89 91 270]
 [49 'Dev Malviya' 15 'Male' 10 'E' 82 83 84 249]
 [50 'Shruti Patil' 15 'Female' 10 'E' 95 94 96 285]]

In [ ]:
df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Roll No,Name,Age,Gender,Class,Section,Math,Science,English,Total
1,1,Aarav Sharma,15,Male,10,A,85,88,90,263
2,2,Ananya Patel,15,Female,10,A,92,95,91,278
3,3,Rohan Gupta,16,Male,10,A,78,80,82,240
4,4,Priya Singh,15,Female,10,A,89,87,93,269

In [ ]:
df.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
46,46,Nikita Sharma,15,Female,10,E,93,92,94,279
47,47,Pranav Nanda,15,Male,10,E,70,72,71,213
48,48,Radhika Joshi,16,Female,10,E,90,89,91,270
49,49,Dev Malviya,15,Male,10,E,82,83,84,249
50,50,Shruti Patil,15,Female,10,E,95,94,96,285

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  51 non-null     object
 1   Unnamed: 1  51 non-null     object
 2   Unnamed: 2  51 non-null     object
 3   Unnamed: 3  51 non-null     object
 4   Unnamed: 4  51 non-null     object
 5   Unnamed: 5  51 non-null     object
 6   Unnamed: 6  51 non-null     object
 7   Unnamed: 7  51 non-null     object
 8   Unnamed: 8  51 non-null     object
 9   Unnamed: 9  51 non-null     object
dtypes: object(10)
memory usage: 4.1+ KB

In [ ]:
df.count()

Unnamed: 0    51
Unnamed: 1    51
Unnamed: 2    51
Unnamed: 3    51
Unnamed: 4    51
Unnamed: 5    51
Unnamed: 6    51
Unnamed: 7    51
Unnamed: 8    51
Unnamed: 9    51
dtype: int64

In [ ]:
df.describe()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
count,51,51,51,51,51,51,51,51,51,51
unique,51,51,3,3,2,6,31,27,28,37
top,Roll No,Name,15,Male,10,A,89,89,90,285
freq,1,1,34,25,50,10,3,4,4,3

In [ ]:
df.loc[0:10]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Roll No,Name,Age,Gender,Class,Section,Math,Science,English,Total
1,1,Aarav Sharma,15,Male,10,A,85,88,90,263
2,2,Ananya Patel,15,Female,10,A,92,95,91,278
3,3,Rohan Gupta,16,Male,10,A,78,80,82,240
4,4,Priya Singh,15,Female,10,A,89,87,93,269
5,5,Arjun Kumar,15,Male,10,A,76,79,75,230
6,6,Sneha Verma,16,Female,10,A,94,91,95,280
7,7,Rahul Joshi,15,Male,10,A,68,72,70,210
8,8,Neha Reddy,15,Female,10,A,81,84,86,251
9,9,Karan Mehta,16,Male,10,A,88,85,87,260
10,10,Pooja Nair,15,Female,10,A,90,89,92,271

In [ ]:
import pandas as pd
df=pd.read_csv(r"/content/std2.csv")
df.head()

,Purchase_ID,Customer_ID,Purchase_Date,Brand,Model,Color,RAM_GB,Storage_GB,Price_USD,Payment_Method,Purchase_Channel,Warranty_Years,Discount_Percent,Final_Amount,Customer_Rating
0,P001,C1001,2025-01-05,Samsung,Galaxy A54,Black,8,128,399,Credit Card,Online,2,10,359.10,5
1,P002,C1002,2025-01-08,Apple,iPhone 15,Blue,6,128,799,Debit Card,Store,1,5,759.05,5
2,P003,C1003,2025-01-10,Xiaomi,Redmi Note 13,Green,8,256,249,UPI,Online,1,15,211.65,4
3,P004,C1004,2025-01-12,OnePlus,Nord CE 4,Gray,8,256,329,Cash,Store,2,8,302.68,4
4,P005,C1005,2025-01-15,Google,Pixel 8,Black,8,128,699,Credit Card,Online,2,12,615.12,5

In [ ]:
df.head()

,Purchase_ID,Customer_ID,Purchase_Date,Brand,Model,Color,RAM_GB,Storage_GB,Price_USD,Payment_Method,Purchase_Channel,Warranty_Years,Discount_Percent,Final_Amount,Customer_Rating
0,P001,C1001,2025-01-05,Samsung,Galaxy A54,Black,8,128,399,Credit Card,Online,2,10,359.10,5
1,P002,C1002,2025-01-08,Apple,iPhone 15,Blue,6,128,799,Debit Card,Store,1,5,759.05,5
2,P003,C1003,2025-01-10,Xiaomi,Redmi Note 13,Green,8,256,249,UPI,Online,1,15,211.65,4
3,P004,C1004,2025-01-12,OnePlus,Nord CE 4,Gray,8,256,329,Cash,Store,2,8,302.68,4
4,P005,C1005,2025-01-15,Google,Pixel 8,Black,8,128,699,Credit Card,Online,2,12,615.12,5

In [ ]:
df.tail()

,Purchase_ID,Customer_ID,Purchase_Date,Brand,Model,Color,RAM_GB,Storage_GB,Price_USD,Payment_Method,Purchase_Channel,Warranty_Years,Discount_Percent,Final_Amount,Customer_Rating
45,P046,C1046,2025-05-17,Motorola,G34,Black,8,128,199,Cash,Online,1,10,179.10,4
46,P047,C1047,2025-05-20,Realme,12 Pro+,Gold,12,256,429,Credit Card,Store,2,12,377.52,5
47,P048,C1048,2025-05-23,Vivo,Y28,Green,8,128,229,UPI,Online,1,8,210.68,4
48,P049,C1049,2025-05-26,Oppo,A60,Blue,8,256,219,Cash,Store,1,5,208.05,4
49,P050,C1050,2025-05-29,Nothing,Phone (2a),White,12,256,379,Credit Card,Online,2,10,341.10,5

In [ ]:
df.describe()

,RAM_GB,Storage_GB,Price_USD,Warranty_Years,Discount_Percent,Final_Amount,Customer_Rating
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000
mean,9.280000,217.600000,508.200000,1.600000,9.140000,457.99340,4.440000
std,3.326087,109.714286,359.272735,0.494872,3.057343,312.57855,0.611455
min,4.000000,64.000000,129.000000,1.000000,5.000000,122.55000,3.000000
25%,8.000000,128.000000,264.000000,1.000000,7.000000,248.07500,4.000000
50%,8.000000,256.000000,399.000000,2.000000,10.000000,359.10000,4.500000
75%,12.000000,256.000000,674.000000,2.000000,10.000000,599.11000,5.000000
max,16.000000,512.000000,1799.000000,2.000000,15.000000,1529.15000,5.000000

In [ ]:
df.count()

Purchase_ID         50
Customer_ID         50
Purchase_Date       50
Brand               50
Model               50
Color               50
RAM_GB              50
Storage_GB          50
Price_USD           50
Payment_Method      50
Purchase_Channel    50
Warranty_Years      50
Discount_Percent    50
Final_Amount        50
Customer_Rating     50
dtype: int64

In [ ]:
df.ndim

2

In [ ]:
df["Brand"].unique()

array(['Samsung', 'Apple', 'Xiaomi', 'OnePlus', 'Google', 'Motorola',
       'Realme', 'Vivo', 'Oppo', 'Nokia', '14 Ultra', 'Nothing'],
      dtype=object)

In [ ]:
df["Model"].unique()

array(['Galaxy A54', 'iPhone 15', 'Redmi Note 13', 'Nord CE 4', 'Pixel 8',
       'G54', 'Narzo 70', 'V30', 'Reno 11', 'G42', 'Galaxy S24',
       'iPhone 14', 'Poco X6', '12R', 'Pixel 7a', 'Edge 50', 'GT 6T',
       'T3', 'F27 Pro', 'C32', 'Galaxy M35', 'iPhone SE', 'Redmi 13C',
       'Nord 3', 'Pixel Fold', 'Moto G84', 'C67', 'Y200', 'A79', 'X30',
       'Galaxy Z Flip6', 'iPhone 15 Pro', '2025-04-07', 'Open', 'Pixel 9',
       'Razr 50', 'P1', 'X100', 'Find X7', 'G22', 'Galaxy A35',
       'iPhone 13', 'Poco F6', 'Nord N30', 'Pixel 8a', 'G34', '12 Pro+',
       'Y28', 'A60', 'Phone (2a)'], dtype=object)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Purchase_ID       50 non-null     object
 1   Customer_ID       50 non-null     object
 2   Purchase_Date     50 non-null     object
 3   Brand             50 non-null     object
 4   Model             50 non-null     object
 5   Color             50 non-null     object
 6   RAM_GB            50 non-null     int64
 7   Storage_GB        50 non-null     int64
 8   Price_USD         50 non-null     int64
 9   Payment_Method    50 non-null     object
 10  Purchase_Channel  50 non-null     object
 11  Warranty_Years    50 non-null     int64
 12  Discount_Percent  50 non-null     int64
 13  Final_Amount      50 non-null     float64
 14  Customer_Rating   50 non-null     int64
dtypes: float64(1), int64(6), object(8)
memory usage: 6.0+ KB

In [ ]:
df[df["Brand"].isin(["Nothing","Oppo"])]

,Purchase_ID,Customer_ID,Purchase_Date,Brand,Model,Color,RAM_GB,Storage_GB,Price_USD,Payment_Method,Purchase_Channel,Warranty_Years,Discount_Percent,Final_Amount,Customer_Rating
8,P009,C1009,2025-01-25,Oppo,Reno 11,White,8,256,379,UPI,Online,2,7,352.47,4
18,P019,C1019,2025-02-23,Oppo,F27 Pro,Green,8,256,349,Credit Card,Online,2,10,314.10,4
28,P029,C1029,2025-03-24,Oppo,A79,Black,8,128,249,Credit Card,Online,2,10,224.10,4
38,P039,C1039,2025-04-25,Oppo,Find X7,White,16,512,999,UPI,Store,2,12,879.12,5
48,P049,C1049,2025-05-26,Oppo,A60,Blue,8,256,219,Cash,Store,1,5,208.05,4
49,P050,C1050,2025-05-29,Nothing,Phone (2a),White,12,256,379,Credit Card,Online,2,10,341.10,5

In [ ]:
df[df["Price_USD"].between(249,349)]

,Purchase_ID,Customer_ID,Purchase_Date,Brand,Model,Color,RAM_GB,Storage_GB,Price_USD,Payment_Method,Purchase_Channel,Warranty_Years,Discount_Percent,Final_Amount,Customer_Rating
2,P003,C1003,2025-01-10,Xiaomi,Redmi Note 13,Green,8,256,249,UPI,Online,1,15,211.65,4
3,P004,C1004,2025-01-12,OnePlus,Nord CE 4,Gray,8,256,329,Cash,Store,2,8,302.68,4
12,P013,C1013,2025-02-06,Xiaomi,Poco X6,Blue,12,256,299,UPI,Online,1,10,269.10,4
17,P018,C1018,2025-02-20,Vivo,T3,Blue,8,128,279,UPI,Store,1,8,256.68,4
18,P019,C1019,2025-02-23,Oppo,F27 Pro,Green,8,256,349,Credit Card,Online,2,10,314.10,4
20,P021,C1021,2025-03-01,Samsung,Galaxy M35,Blue,8,256,329,UPI,Online,2,10,296.10,5
25,P026,C1026,2025-03-15,Motorola,Moto G84,Blue,12,256,299,UPI,Store,2,8,275.08,4
27,P028,C1028,2025-03-21,Vivo,Y200,Purple,8,128,259,Debit Card,Store,1,5,246.05,4
28,P029,C1029,2025-03-24,Oppo,A79,Black,8,128,249,Credit Card,Online,2,10,224.10,4
36,P037,C1037,2025-04-19,Realme,P1,Green,8,256,289,Cash,Store,1,5,274.55,4
40,P041,C1041,2025-05-02,Samsung,Galaxy A35,Blue,8,128,349,Credit Card,Store,2,10,314.10,5
43,P044,C1044,2025-05-11,OnePlus,Nord N30,Gray,8,128,299,Credit Card,Online,2,15,254.15,4