In [ ]:
import pandas as pd
import numpy as np
student={
    "id":[101,102,103,104,105],"name":["anuu","sujji",np.nan,"sneha","kiran"],
    "department":["BCA","BCA","BSc",np.nan,"BCA"],
    "marks":[85,np.nan,78,92,80]
}
print(type(student))
df=pd.DataFrame(student)
print(df)

<class 'dict'>
    id   name department  marks
0  101   anuu        BCA   85.0
1  102  sujji        BCA    NaN
2  103    NaN        BSc   78.0
3  104  sneha        NaN   92.0
4  105  kiran        BCA   80.0

In [ ]:
df.isnull()

      id   name  department  marks
0  False  False       False  False
1  False  False       False   True
2  False   True       False  False
3  False  False        True  False
4  False  False       False  False

In [ ]:
df.notnull()

     id   name  department  marks
0  True   True        True   True
1  True   True        True  False
2  True  False        True   True
3  True   True       False   True
4  True   True        True   True

In [ ]:
print(df.fillna("unknown"))

    id     name department    marks
0  101     anuu        BCA     85.0
1  102    sujji        BCA  unknown
2  103  unknown        BSc     78.0
3  104    sneha    unknown     92.0
4  105    kiran        BCA     80.0

In [ ]:
df["marks"]=df["marks"].fillna(0)
print(df)

    id   name department  marks
0  101   anuu        BCA   85.0
1  102  sujji        BCA    0.0
2  103    NaN        BSc   78.0
3  104  sneha        NaN   92.0
4  105  kiran        BCA   80.0

In [ ]:
import pandas as pd
import numpy as np
student={
    "id":[101,102,103,104,105],"name":["anuu","sujji",np.nan,"sneha","kiran"],
    "department":["BCA","BCA","BSc",np.nan,"BCA"],
    "marks":[85,np.nan,78,92,80]
}
df=pd.DataFrame(student)
print(df)

    id   name department  marks
0  101   anuu        BCA   85.0
1  102  sujji        BCA    NaN
2  103    NaN        BSc   78.0
3  104  sneha        NaN   92.0
4  105  kiran        BCA   80.0

In [ ]:
df.dropna()

    id   name department  marks
0  101   anuu        BCA   85.0
4  105  kiran        BCA   80.0

In [ ]:
import pandas as pd
df=pd.read_csv(r"/content/cricket.csv")
df.head()

,match_id,match_date,season,team,opponent,player,runs,match_total,century
0,IPL2025_001,2025-03-22,2025,CSK,MI,Ruturaj Gaikwad,78,198,No
1,IPL2025_001,2025-03-22,2025,CSK,MI,Shivam Dube,45,198,No
2,IPL2025_001,2025-03-22,2025,MI,CSK,Rohit Sharma,66,186,No
3,IPL2025_001,2025-03-22,2025,MI,CSK,Suryakumar Yadav,74,186,No
4,IPL2025_002,2025-03-23,2025,RCB,KKR,Virat Kohli,114,221,Yes

In [ ]:
df["player"].value_counts()

player
Ruturaj Gaikwad     2
Virat Kohli         2
Abhishek Sharma     2
Rohit Sharma        1
Suryakumar Yadav    1
Rajat Patidar       1
Shivam Dube         1
Andre Russell       1
Travis Head         1
Heinrich Klaasen    1
Yashasvi Jaiswal    1
Sanju Samson        1
Shubman Gill        1
David Miller        1
Shreyas Iyer        1
Rishabh Pant        1
David Warner        1
Nicholas Pooran     1
KL Rahul            1
Liam Livingstone    1
Sunil Narine        1
Rinku Singh         1
Shikhar Dhawan      1
MS Dhoni            1
Jos Buttler         1
Riyan Parag         1
Faf du Plessis      1
Glenn Maxwell       1
Ishan Kishan        1
Hardik Pandya       1
Ravindra Jadeja     1
Sai Sudharsan       1
Rahul Tewatia       1
Prithvi Shaw        1
Axar Patel          1
Aiden Markram       1
Jitesh Sharma       1
Sam Curran          1
Tilak Varma         1
Tim David           1
Rachin Ravindra     1
Daryl Mitchell      1
Wriddhiman Saha     1
Rashid Khan         1
Cameron Green       1
Quinton de Kock     1
Marcus Stoinis      1
Name: count, dtype: int64

In [ ]:
df["player"].unique()

array(['Ruturaj Gaikwad', 'Shivam Dube', 'Rohit Sharma',
       'Suryakumar Yadav', 'Virat Kohli', 'Rajat Patidar', 'Shreyas Iyer',
       'Andre Russell', 'Travis Head', 'Heinrich Klaasen',
       'Yashasvi Jaiswal', 'Sanju Samson', 'Shubman Gill', 'David Miller',
       'Rishabh Pant', 'David Warner', 'KL Rahul', 'Nicholas Pooran',
       'Shikhar Dhawan', 'Liam Livingstone', 'Sunil Narine',
       'Rinku Singh', 'Ravindra Jadeja', 'MS Dhoni', 'Jos Buttler',
       'Riyan Parag', 'Faf du Plessis', 'Glenn Maxwell', 'Ishan Kishan',
       'Hardik Pandya', 'Sai Sudharsan', 'Rahul Tewatia', 'Prithvi Shaw',
       'Axar Patel', 'Abhishek Sharma', 'Aiden Markram', 'Jitesh Sharma',
       'Sam Curran', 'Tilak Varma', 'Tim David', 'Rachin Ravindra',
       'Daryl Mitchell', 'Wriddhiman Saha', 'Rashid Khan',
       'Cameron Green', 'Quinton de Kock', 'Marcus Stoinis'], dtype=object)

In [ ]:
df["player"].nunique()

47

In [ ]:
import pandas as pd
df=pd.read_csv(r"/content/cricket.csv")
df

,match_id,match_date,season,team,opponent,player,runs,match_total,century
0,IPL2025_001,2025-03-22,2025,CSK,MI,Ruturaj Gaikwad,78,198,No
1,IPL2025_001,2025-03-22,2025,CSK,MI,Shivam Dube,45,198,No
2,IPL2025_001,2025-03-22,2025,MI,CSK,Rohit Sharma,66,186,No
3,IPL2025_001,2025-03-22,2025,MI,CSK,Suryakumar Yadav,74,186,No
4,IPL2025_002,2025-03-23,2025,RCB,KKR,Virat Kohli,114,221,Yes
5,IPL2025_002,2025-03-23,2025,RCB,KKR,Rajat Patidar,43,221,No
6,IPL2025_002,2025-03-23,2025,KKR,RCB,Shreyas Iyer,71,205,No
7,IPL2025_002,2025-03-23,2025,KKR,RCB,Andre Russell,58,205,No
8,IPL2025_003,2025-03-24,2025,SRH,RR,Travis Head,103,234,Yes
9,IPL2025_003,2025-03-24,2025,SRH,RR,Heinrich Klaasen,68,234,No
10,IPL2025_003,2025-03-24,2025,RR,SRH,Yashasvi Jaiswal,91,214,No
11,IPL2025_003,2025-03-24,2025,RR,SRH,Sanju Samson,55,214,No
12,IPL2025_004,2025-03-25,2025,GT,DC,Shubman Gill,96,212,No
13,IPL2025_004,2025-03-25,2025,GT,DC,David Miller,47,212,No
14,IPL2025_004,2025-03-25,2025,DC,GT,Rishabh Pant,82,198,No
15,IPL2025_004,2025-03-25,2025,DC,GT,David Warner,52,198,No
16,IPL2025_005,2025-03-26,2025,LSG,PBKS,KL Rahul,108,226,Yes
17,IPL2025_005,2025-03-26,2025,LSG,PBKS,Nicholas Pooran,64,226,No
18,IPL2025_005,2025-03-26,2025,PBKS,LSG,Shikhar Dhawan,77,202,No
19,IPL2025_005,2025-03-26,2025,PBKS,LSG,Liam Livingstone,59,202,No
20,IPL2025_006,2025-03-27,2025,KKR,CSK,Sunil Narine,73,207,No
21,IPL2025_006,2025-03-27,2025,KKR,CSK,Rinku Singh,54,207,No
22,IPL2025_006,2025-03-27,2025,CSK,KKR,Ravindra Jadeja,49,191,No
23,IPL2025_006,2025-03-27,2025,CSK,KKR,MS Dhoni,37,191,No
24,IPL2025_007,2025-03-28,2025,RR,RCB,Jos Buttler,105,224,Yes
25,IPL2025_007,2025-03-28,2025,RR,RCB,Riyan Parag,48,224,No
26,IPL2025_007,2025-03-28,2025,RCB,RR,Faf du Plessis,81,210,No
27,IPL2025_007,2025-03-28,2025,RCB,RR,Glenn Maxwell,56,210,No
28,IPL2025_008,2025-03-29,2025,MI,GT,Ishan Kishan,90,216,No
29,IPL2025_008,2025-03-29,2025,MI,GT,Hardik Pandya,61,216,No
30,IPL2025_008,2025-03-29,2025,GT,MI,Sai Sudharsan,75,201,No
31,IPL2025_008,2025-03-29,2025,GT,MI,Rahul Tewatia,42,201,No
32,IPL2025_009,2025-03-30,2025,DC,SRH,Prithvi Shaw,84,208,No
33,IPL2025_009,2025-03-30,2025,DC,SRH,Axar Patel,39,208,No
34,IPL2025_009,2025-03-30,2025,SRH,DC,Abhishek Sharma,97,203,No
35,IPL2025_009,2025-03-30,2025,SRH,DC,Aiden Markram,46,203,No
36,IPL2025_010,2025-03-31,2025,PBKS,MI,Jitesh Sharma,69,196,No
37,IPL2025_010,2025-03-31,2025,PBKS,MI,Sam Curran,50,196,No
38,IPL2025_010,2025-03-31,2025,MI,PBKS,Tilak Varma,86,202,No
39,IPL2025_010,2025-03-31,2025,MI,PBKS,Tim David,40,202,No
40,IPL2025_011,2025-04-01,2025,CSK,GT,Rachin Ravindra,107,231,Yes
41,IPL2025_011,2025-04-01,2025,CSK,GT,Daryl Mitchell,58,231,No
42,IPL2025_011,2025-04-01,2025,GT,CSK,Wriddhiman Saha,61,199,No
43,IPL2025_011,2025-04-01,2025,GT,CSK,Rashid Khan,29,199,No
44,IPL2025_012,2025-04-02,2025,RCB,LSG,Virat Kohli,94,218,No
45,IPL2025_012,2025-04-02,2025,RCB,LSG,Cameron Green,57,218,No
46,IPL2025_012,2025-04-02,2025,LSG,RCB,Quinton de Kock,81,206,No
47,IPL2025_012,2025-04-02,2025,LSG,RCB,Marcus Stoinis,65,206,No
48,IPL2025_013,2025-04-03,2025,SRH,CSK,Abhishek Sharma,112,239,Yes
49,IPL2025_013,2025-04-03,2025,CSK,SRH,Ruturaj Gaikwad,88,214,No

In [ ]:
df.head()

,match_id,match_date,season,team,opponent,player,runs,match_total,century
0,IPL2025_001,2025-03-22,2025,CSK,MI,Ruturaj Gaikwad,78,198,No
1,IPL2025_001,2025-03-22,2025,CSK,MI,Shivam Dube,45,198,No
2,IPL2025_001,2025-03-22,2025,MI,CSK,Rohit Sharma,66,186,No
3,IPL2025_001,2025-03-22,2025,MI,CSK,Suryakumar Yadav,74,186,No
4,IPL2025_002,2025-03-23,2025,RCB,KKR,Virat Kohli,114,221,Yes

In [ ]:
df.tail()

,match_id,match_date,season,team,opponent,player,runs,match_total,century
45,IPL2025_012,2025-04-02,2025,RCB,LSG,Cameron Green,57,218,No
46,IPL2025_012,2025-04-02,2025,LSG,RCB,Quinton de Kock,81,206,No
47,IPL2025_012,2025-04-02,2025,LSG,RCB,Marcus Stoinis,65,206,No
48,IPL2025_013,2025-04-03,2025,SRH,CSK,Abhishek Sharma,112,239,Yes
49,IPL2025_013,2025-04-03,2025,CSK,SRH,Ruturaj Gaikwad,88,214,No

In [ ]:
df.ndim

2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   match_id     50 non-null     object
 1   match_date   50 non-null     object
 2   season       50 non-null     int64
 3   team         50 non-null     object
 4   opponent     50 non-null     object
 5   player       50 non-null     object
 6   runs         50 non-null     int64
 7   match_total  50 non-null     int64
 8   century      50 non-null     object
dtypes: int64(3), object(6)
memory usage: 3.6+ KB

In [ ]:
df.describe()

       season        runs  match_total
count    50.0   50.000000    50.000000
mean   2025.0   69.700000   209.380000
std       0.0   22.127875    12.750174
min    2025.0   29.000000   186.000000
25%    2025.0   52.500000   201.000000
50%    2025.0   67.000000   207.000000
75%    2025.0   85.500000   217.500000
max    2025.0  114.000000   239.000000

In [ ]:
df.count()

match_id       50
match_date     50
season         50
team           50
opponent       50
player         50
runs           50
match_total    50
century        50
dtype: int64

In [ ]:
avg=df["runs"].mean()

In [ ]:
df.size

450

In [ ]:
df.shape

(50, 9)

In [ ]:
df.columns

Index(['match_id', 'match_date', 'season', 'team', 'opponent', 'player',
       'runs', 'match_total', 'century'],
      dtype='object')

In [ ]:
df.axes

[RangeIndex(start=0, stop=50, step=1),
 Index(['match_id', 'match_date', 'season', 'team', 'opponent', 'player',
        'runs', 'match_total', 'century'],
       dtype='object')]

In [ ]:
df.dtypes

match_id       object
match_date     object
season          int64
team           object
opponent       object
player         object
runs            int64
match_total     int64
century        object
dtype: object

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
match_id,IPL2025_001,IPL2025_001,IPL2025_001,IPL2025_001,IPL2025_002,IPL2025_002,IPL2025_002,IPL2025_002,IPL2025_003,IPL2025_003,...,IPL2025_011,IPL2025_011,IPL2025_011,IPL2025_011,IPL2025_012,IPL2025_012,IPL2025_012,IPL2025_012,IPL2025_013,IPL2025_013
match_date,2025-03-22,2025-03-22,2025-03-22,2025-03-22,2025-03-23,2025-03-23,2025-03-23,2025-03-23,2025-03-24,2025-03-24,...,2025-04-01,2025-04-01,2025-04-01,2025-04-01,2025-04-02,2025-04-02,2025-04-02,2025-04-02,2025-04-03,2025-04-03
season,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025,...,2025,2025,2025,2025,2025,2025,2025,2025,2025,2025
team,CSK,CSK,MI,MI,RCB,RCB,KKR,KKR,SRH,SRH,...,CSK,CSK,GT,GT,RCB,RCB,LSG,LSG,SRH,CSK
opponent,MI,MI,CSK,CSK,KKR,KKR,RCB,RCB,RR,RR,...,GT,GT,CSK,CSK,LSG,LSG,RCB,RCB,CSK,SRH
player,Ruturaj Gaikwad,Shivam Dube,Rohit Sharma,Suryakumar Yadav,Virat Kohli,Rajat Patidar,Shreyas Iyer,Andre Russell,Travis Head,Heinrich Klaasen,...,Rachin Ravindra,Daryl Mitchell,Wriddhiman Saha,Rashid Khan,Virat Kohli,Cameron Green,Quinton de Kock,Marcus Stoinis,Abhishek Sharma,Ruturaj Gaikwad
runs,78,45,66,74,114,43,71,58,103,68,...,107,58,61,29,94,57,81,65,112,88
match_total,198,198,186,186,221,221,205,205,234,234,...,231,231,199,199,218,218,206,206,239,214
century,No,No,No,No,Yes,No,No,No,Yes,No,...,Yes,No,No,No,No,No,No,No,Yes,No

In [ ]:
df.empty

False

In [ ]:
df.values

array([['IPL2025_001', '2025-03-22', 2025, 'CSK', 'MI',
        'Ruturaj Gaikwad', 78, 198, 'No'],
       ['IPL2025_001', '2025-03-22', 2025, 'CSK', 'MI', 'Shivam Dube',
        45, 198, 'No'],
       ['IPL2025_001', '2025-03-22', 2025, 'MI', 'CSK', 'Rohit Sharma',
        66, 186, 'No'],
       ['IPL2025_001', '2025-03-22', 2025, 'MI', 'CSK',
        'Suryakumar Yadav', 74, 186, 'No'],
       ['IPL2025_002', '2025-03-23', 2025, 'RCB', 'KKR', 'Virat Kohli',
        114, 221, 'Yes'],
       ['IPL2025_002', '2025-03-23', 2025, 'RCB', 'KKR', 'Rajat Patidar',
        43, 221, 'No'],
       ['IPL2025_002', '2025-03-23', 2025, 'KKR', 'RCB', 'Shreyas Iyer',
        71, 205, 'No'],
       ['IPL2025_002', '2025-03-23', 2025, 'KKR', 'RCB', 'Andre Russell',
        58, 205, 'No'],
       ['IPL2025_003', '2025-03-24', 2025, 'SRH', 'RR', 'Travis Head',
        103, 234, 'Yes'],
       ['IPL2025_003', '2025-03-24', 2025, 'SRH', 'RR',
        'Heinrich Klaasen', 68, 234, 'No'],
       ['IPL2025_003', '2025-03-24', 2025, 'RR', 'SRH',
        'Yashasvi Jaiswal', 91, 214, 'No'],
       ['IPL2025_003', '2025-03-24', 2025, 'RR', 'SRH', 'Sanju Samson',
        55, 214, 'No'],
       ['IPL2025_004', '2025-03-25', 2025, 'GT', 'DC', 'Shubman Gill',
        96, 212, 'No'],
       ['IPL2025_004', '2025-03-25', 2025, 'GT', 'DC', 'David Miller',
        47, 212, 'No'],
       ['IPL2025_004', '2025-03-25', 2025, 'DC', 'GT', 'Rishabh Pant',
        82, 198, 'No'],
       ['IPL2025_004', '2025-03-25', 2025, 'DC', 'GT', 'David Warner',
        52, 198, 'No'],
       ['IPL2025_005', '2025-03-26', 2025, 'LSG', 'PBKS', 'KL Rahul',
        108, 226, 'Yes'],
       ['IPL2025_005', '2025-03-26', 2025, 'LSG', 'PBKS',
        'Nicholas Pooran', 64, 226, 'No'],
       ['IPL2025_005', '2025-03-26', 2025, 'PBKS', 'LSG',
        'Shikhar Dhawan', 77, 202, 'No'],
       ['IPL2025_005', '2025-03-26', 2025, 'PBKS', 'LSG',
        'Liam Livingstone', 59, 202, 'No'],
       ['IPL2025_006', '2025-03-27', 2025, 'KKR', 'CSK', 'Sunil Narine',
        73, 207, 'No'],
       ['IPL2025_006', '2025-03-27', 2025, 'KKR', 'CSK', 'Rinku Singh',
        54, 207, 'No'],
       ['IPL2025_006', '2025-03-27', 2025, 'CSK', 'KKR',
        'Ravindra Jadeja', 49, 191, 'No'],
       ['IPL2025_006', '2025-03-27', 2025, 'CSK', 'KKR', 'MS Dhoni', 37,
        191, 'No'],
       ['IPL2025_007', '2025-03-28', 2025, 'RR', 'RCB', 'Jos Buttler',
        105, 224, 'Yes'],
       ['IPL2025_007', '2025-03-28', 2025, 'RR', 'RCB', 'Riyan Parag',
        48, 224, 'No'],
       ['IPL2025_007', '2025-03-28', 2025, 'RCB', 'RR', 'Faf du Plessis',
        81, 210, 'No'],
       ['IPL2025_007', '2025-03-28', 2025, 'RCB', 'RR', 'Glenn Maxwell',
        56, 210, 'No'],
       ['IPL2025_008', '2025-03-29', 2025, 'MI', 'GT', 'Ishan Kishan',
        90, 216, 'No'],
       ['IPL2025_008', '2025-03-29', 2025, 'MI', 'GT', 'Hardik Pandya',
        61, 216, 'No'],
       ['IPL2025_008', '2025-03-29', 2025, 'GT', 'MI', 'Sai Sudharsan',
        75, 201, 'No'],
       ['IPL2025_008', '2025-03-29', 2025, 'GT', 'MI', 'Rahul Tewatia',
        42, 201, 'No'],
       ['IPL2025_009', '2025-03-30', 2025, 'DC', 'SRH', 'Prithvi Shaw',
        84, 208, 'No'],
       ['IPL2025_009', '2025-03-30', 2025, 'DC', 'SRH', 'Axar Patel', 39,
        208, 'No'],
       ['IPL2025_009', '2025-03-30', 2025, 'SRH', 'DC',
        'Abhishek Sharma', 97, 203, 'No'],
       ['IPL2025_009', '2025-03-30', 2025, 'SRH', 'DC', 'Aiden Markram',
        46, 203, 'No'],
       ['IPL2025_010', '2025-03-31', 2025, 'PBKS', 'MI', 'Jitesh Sharma',
        69, 196, 'No'],
       ['IPL2025_010', '2025-03-31', 2025, 'PBKS', 'MI', 'Sam Curran',
        50, 196, 'No'],
       ['IPL2025_010', '2025-03-31', 2025, 'MI', 'PBKS', 'Tilak Varma',
        86, 202, 'No'],
       ['IPL2025_010', '2025-03-31', 2025, 'MI', 'PBKS', 'Tim David', 40,
        202, 'No'],
       ['IPL2025_011', '2025-04-01', 2025, 'CSK', 'GT',
        'Rachin Ravindra', 107, 231, 'Yes'],
       ['IPL2025_011', '2025-04-01', 2025, 'CSK', 'GT', 'Daryl Mitchell',
        58, 231, 'No'],
       ['IPL2025_011', '2025-04-01', 2025, 'GT', 'CSK',
        'Wriddhiman Saha', 61, 199, 'No'],
       ['IPL2025_011', '2025-04-01', 2025, 'GT', 'CSK', 'Rashid Khan',
        29, 199, 'No'],
       ['IPL2025_012', '2025-04-02', 2025, 'RCB', 'LSG', 'Virat Kohli',
        94, 218, 'No'],
       ['IPL2025_012', '2025-04-02', 2025, 'RCB', 'LSG', 'Cameron Green',
        57, 218, 'No'],
       ['IPL2025_012', '2025-04-02', 2025, 'LSG', 'RCB',
        'Quinton de Kock', 81, 206, 'No'],
       ['IPL2025_012', '2025-04-02', 2025, 'LSG', 'RCB',
        'Marcus Stoinis', 65, 206, 'No'],
       ['IPL2025_013', '2025-04-03', 2025, 'SRH', 'CSK',
        'Abhishek Sharma', 112, 239, 'Yes'],
       ['IPL2025_013', '2025-04-03', 2025, 'CSK', 'SRH',
        'Ruturaj Gaikwad', 88, 214, 'No']], dtype=object)

In [ ]:
df.head()

    id   name department  marks
0  101   anuu        BCA   85.0
1  102  sujji        BCA    NaN
2  103    NaN        BSc   78.0
3  104  sneha        NaN   92.0
4  105  kiran        BCA   80.0

In [ ]:
df.rename(columns={"player":"cricketer"})

,match_id,match_date,season,team,opponent,cricketer,runs,match_total,century
0,IPL2025_001,2025-03-22,2025,CSK,MI,Ruturaj Gaikwad,78,198,No
1,IPL2025_001,2025-03-22,2025,CSK,MI,Shivam Dube,45,198,No
2,IPL2025_001,2025-03-22,2025,MI,CSK,Rohit Sharma,66,186,No
3,IPL2025_001,2025-03-22,2025,MI,CSK,Suryakumar Yadav,74,186,No
4,IPL2025_002,2025-03-23,2025,RCB,KKR,Virat Kohli,114,221,Yes
5,IPL2025_002,2025-03-23,2025,RCB,KKR,Rajat Patidar,43,221,No
6,IPL2025_002,2025-03-23,2025,KKR,RCB,Shreyas Iyer,71,205,No
7,IPL2025_002,2025-03-23,2025,KKR,RCB,Andre Russell,58,205,No
8,IPL2025_003,2025-03-24,2025,SRH,RR,Travis Head,103,234,Yes
9,IPL2025_003,2025-03-24,2025,SRH,RR,Heinrich Klaasen,68,234,No
10,IPL2025_003,2025-03-24,2025,RR,SRH,Yashasvi Jaiswal,91,214,No
11,IPL2025_003,2025-03-24,2025,RR,SRH,Sanju Samson,55,214,No
12,IPL2025_004,2025-03-25,2025,GT,DC,Shubman Gill,96,212,No
13,IPL2025_004,2025-03-25,2025,GT,DC,David Miller,47,212,No
14,IPL2025_004,2025-03-25,2025,DC,GT,Rishabh Pant,82,198,No
15,IPL2025_004,2025-03-25,2025,DC,GT,David Warner,52,198,No
16,IPL2025_005,2025-03-26,2025,LSG,PBKS,KL Rahul,108,226,Yes
17,IPL2025_005,2025-03-26,2025,LSG,PBKS,Nicholas Pooran,64,226,No
18,IPL2025_005,2025-03-26,2025,PBKS,LSG,Shikhar Dhawan,77,202,No
19,IPL2025_005,2025-03-26,2025,PBKS,LSG,Liam Livingstone,59,202,No
20,IPL2025_006,2025-03-27,2025,KKR,CSK,Sunil Narine,73,207,No
21,IPL2025_006,2025-03-27,2025,KKR,CSK,Rinku Singh,54,207,No
22,IPL2025_006,2025-03-27,2025,CSK,KKR,Ravindra Jadeja,49,191,No
23,IPL2025_006,2025-03-27,2025,CSK,KKR,MS Dhoni,37,191,No
24,IPL2025_007,2025-03-28,2025,RR,RCB,Jos Buttler,105,224,Yes
25,IPL2025_007,2025-03-28,2025,RR,RCB,Riyan Parag,48,224,No
26,IPL2025_007,2025-03-28,2025,RCB,RR,Faf du Plessis,81,210,No
27,IPL2025_007,2025-03-28,2025,RCB,RR,Glenn Maxwell,56,210,No
28,IPL2025_008,2025-03-29,2025,MI,GT,Ishan Kishan,90,216,No
29,IPL2025_008,2025-03-29,2025,MI,GT,Hardik Pandya,61,216,No
30,IPL2025_008,2025-03-29,2025,GT,MI,Sai Sudharsan,75,201,No
31,IPL2025_008,2025-03-29,2025,GT,MI,Rahul Tewatia,42,201,No
32,IPL2025_009,2025-03-30,2025,DC,SRH,Prithvi Shaw,84,208,No
33,IPL2025_009,2025-03-30,2025,DC,SRH,Axar Patel,39,208,No
34,IPL2025_009,2025-03-30,2025,SRH,DC,Abhishek Sharma,97,203,No
35,IPL2025_009,2025-03-30,2025,SRH,DC,Aiden Markram,46,203,No
36,IPL2025_010,2025-03-31,2025,PBKS,MI,Jitesh Sharma,69,196,No
37,IPL2025_010,2025-03-31,2025,PBKS,MI,Sam Curran,50,196,No
38,IPL2025_010,2025-03-31,2025,MI,PBKS,Tilak Varma,86,202,No
39,IPL2025_010,2025-03-31,2025,MI,PBKS,Tim David,40,202,No
40,IPL2025_011,2025-04-01,2025,CSK,GT,Rachin Ravindra,107,231,Yes
41,IPL2025_011,2025-04-01,2025,CSK,GT,Daryl Mitchell,58,231,No
42,IPL2025_011,2025-04-01,2025,GT,CSK,Wriddhiman Saha,61,199,No
43,IPL2025_011,2025-04-01,2025,GT,CSK,Rashid Khan,29,199,No
44,IPL2025_012,2025-04-02,2025,RCB,LSG,Virat Kohli,94,218,No
45,IPL2025_012,2025-04-02,2025,RCB,LSG,Cameron Green,57,218,No
46,IPL2025_012,2025-04-02,2025,LSG,RCB,Quinton de Kock,81,206,No
47,IPL2025_012,2025-04-02,2025,LSG,RCB,Marcus Stoinis,65,206,No
48,IPL2025_013,2025-04-03,2025,SRH,CSK,Abhishek Sharma,112,239,Yes
49,IPL2025_013,2025-04-03,2025,CSK,SRH,Ruturaj Gaikwad,88,214,No

In [ ]:
df.notnull()

,match_id,match_date,season,team,opponent,player,runs,match_total,century
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True
23,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True
26,True,True,True,True,True,True,True,True,True
27,True,True,True,True,True,True,True,True,True
28,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True
30,True,True,True,True,True,True,True,True,True
31,True,True,True,True,True,True,True,True,True
32,True,True,True,True,True,True,True,True,True
33,True,True,True,True,True,True,True,True,True
34,True,True,True,True,True,True,True,True,True
35,True,True,True,True,True,True,True,True,True
36,True,True,True,True,True,True,True,True,True
37,True,True,True,True,True,True,True,True,True
38,True,True,True,True,True,True,True,True,True
39,True,True,True,True,True,True,True,True,True
40,True,True,True,True,True,True,True,True,True
41,True,True,True,True,True,True,True,True,True
42,True,True,True,True,True,True,True,True,True
43,True,True,True,True,True,True,True,True,True
44,True,True,True,True,True,True,True,True,True
45,True,True,True,True,True,True,True,True,True
46,True,True,True,True,True,True,True,True,True
47,True,True,True,True,True,True,True,True,True
48,True,True,True,True,True,True,True,True,True
49,True,True,True,True,True,True,True,True,True

In [ ]:
print(df.fillna("unknown"))

       match_id  match_date  season  team opponent            player  runs  \
0   IPL2025_001  2025-03-22    2025   CSK       MI   Ruturaj Gaikwad    78
1   IPL2025_001  2025-03-22    2025   CSK       MI       Shivam Dube    45
2   IPL2025_001  2025-03-22    2025    MI      CSK      Rohit Sharma    66
3   IPL2025_001  2025-03-22    2025    MI      CSK  Suryakumar Yadav    74
4   IPL2025_002  2025-03-23    2025   RCB      KKR       Virat Kohli   114
5   IPL2025_002  2025-03-23    2025   RCB      KKR     Rajat Patidar    43
6   IPL2025_002  2025-03-23    2025   KKR      RCB      Shreyas Iyer    71
7   IPL2025_002  2025-03-23    2025   KKR      RCB     Andre Russell    58
8   IPL2025_003  2025-03-24    2025   SRH       RR       Travis Head   103
9   IPL2025_003  2025-03-24    2025   SRH       RR  Heinrich Klaasen    68
10  IPL2025_003  2025-03-24    2025    RR      SRH  Yashasvi Jaiswal    91
11  IPL2025_003  2025-03-24    2025    RR      SRH      Sanju Samson    55
12  IPL2025_004  2025-03-25    2025    GT       DC      Shubman Gill    96
13  IPL2025_004  2025-03-25    2025    GT       DC      David Miller    47
14  IPL2025_004  2025-03-25    2025    DC       GT      Rishabh Pant    82
15  IPL2025_004  2025-03-25    2025    DC       GT      David Warner    52
16  IPL2025_005  2025-03-26    2025   LSG     PBKS          KL Rahul   108
17  IPL2025_005  2025-03-26    2025   LSG     PBKS   Nicholas Pooran    64
18  IPL2025_005  2025-03-26    2025  PBKS      LSG    Shikhar Dhawan    77
19  IPL2025_005  2025-03-26    2025  PBKS      LSG  Liam Livingstone    59
20  IPL2025_006  2025-03-27    2025   KKR      CSK      Sunil Narine    73
21  IPL2025_006  2025-03-27    2025   KKR      CSK       Rinku Singh    54
22  IPL2025_006  2025-03-27    2025   CSK      KKR   Ravindra Jadeja    49
23  IPL2025_006  2025-03-27    2025   CSK      KKR          MS Dhoni    37
24  IPL2025_007  2025-03-28    2025    RR      RCB       Jos Buttler   105
25  IPL2025_007  2025-03-28    2025    RR      RCB       Riyan Parag    48
26  IPL2025_007  2025-03-28    2025   RCB       RR    Faf du Plessis    81
27  IPL2025_007  2025-03-28    2025   RCB       RR     Glenn Maxwell    56
28  IPL2025_008  2025-03-29    2025    MI       GT      Ishan Kishan    90
29  IPL2025_008  2025-03-29    2025    MI       GT     Hardik Pandya    61
30  IPL2025_008  2025-03-29    2025    GT       MI     Sai Sudharsan    75
31  IPL2025_008  2025-03-29    2025    GT       MI     Rahul Tewatia    42
32  IPL2025_009  2025-03-30    2025    DC      SRH      Prithvi Shaw    84
33  IPL2025_009  2025-03-30    2025    DC      SRH        Axar Patel    39
34  IPL2025_009  2025-03-30    2025   SRH       DC   Abhishek Sharma    97
35  IPL2025_009  2025-03-30    2025   SRH       DC     Aiden Markram    46
36  IPL2025_010  2025-03-31    2025  PBKS       MI     Jitesh Sharma    69
37  IPL2025_010  2025-03-31    2025  PBKS       MI        Sam Curran    50
38  IPL2025_010  2025-03-31    2025    MI     PBKS       Tilak Varma    86
39  IPL2025_010  2025-03-31    2025    MI     PBKS         Tim David    40
40  IPL2025_011  2025-04-01    2025   CSK       GT   Rachin Ravindra   107
41  IPL2025_011  2025-04-01    2025   CSK       GT    Daryl Mitchell    58
42  IPL2025_011  2025-04-01    2025    GT      CSK   Wriddhiman Saha    61
43  IPL2025_011  2025-04-01    2025    GT      CSK       Rashid Khan    29
44  IPL2025_012  2025-04-02    2025   RCB      LSG       Virat Kohli    94
45  IPL2025_012  2025-04-02    2025   RCB      LSG     Cameron Green    57
46  IPL2025_012  2025-04-02    2025   LSG      RCB   Quinton de Kock    81
47  IPL2025_012  2025-04-02    2025   LSG      RCB    Marcus Stoinis    65
48  IPL2025_013  2025-04-03    2025   SRH      CSK   Abhishek Sharma   112
49  IPL2025_013  2025-04-03    2025   CSK      SRH   Ruturaj Gaikwad    88

    match_total century
0           198      No
1           198      No
2           186      No
3           186      No
4           221     Yes
5           221      No
6           205      No
7           205      No
8           234     Yes
9           234      No
10          214      No
11          214      No
12          212      No
13          212      No
14          198      No
15          198      No
16          226     Yes
17          226      No
18          202      No
19          202      No
20          207      No
21          207      No
22          191      No
23          191      No
24          224     Yes
25          224      No
26          210      No
27          210      No
28          216      No
29          216      No
30          201      No
31          201      No
32          208      No
33          208      No
34          203      No
35          203      No
36          196      No
37          196      No
38          202      No
39          202      No
40          231     Yes
41          231      No
42          199      No
43          199      No
44          218      No
45          218      No
46          206      No
47          206      No
48          239     Yes
49          214      No

In [ ]:
df.dropna()

,match_id,match_date,season,team,opponent,player,runs,match_total,century
0,IPL2025_001,2025-03-22,2025,CSK,MI,Ruturaj Gaikwad,78,198,No
1,IPL2025_001,2025-03-22,2025,CSK,MI,Shivam Dube,45,198,No
2,IPL2025_001,2025-03-22,2025,MI,CSK,Rohit Sharma,66,186,No
3,IPL2025_001,2025-03-22,2025,MI,CSK,Suryakumar Yadav,74,186,No
4,IPL2025_002,2025-03-23,2025,RCB,KKR,Virat Kohli,114,221,Yes
5,IPL2025_002,2025-03-23,2025,RCB,KKR,Rajat Patidar,43,221,No
6,IPL2025_002,2025-03-23,2025,KKR,RCB,Shreyas Iyer,71,205,No
7,IPL2025_002,2025-03-23,2025,KKR,RCB,Andre Russell,58,205,No
8,IPL2025_003,2025-03-24,2025,SRH,RR,Travis Head,103,234,Yes
9,IPL2025_003,2025-03-24,2025,SRH,RR,Heinrich Klaasen,68,234,No
10,IPL2025_003,2025-03-24,2025,RR,SRH,Yashasvi Jaiswal,91,214,No
11,IPL2025_003,2025-03-24,2025,RR,SRH,Sanju Samson,55,214,No
12,IPL2025_004,2025-03-25,2025,GT,DC,Shubman Gill,96,212,No
13,IPL2025_004,2025-03-25,2025,GT,DC,David Miller,47,212,No
14,IPL2025_004,2025-03-25,2025,DC,GT,Rishabh Pant,82,198,No
15,IPL2025_004,2025-03-25,2025,DC,GT,David Warner,52,198,No
16,IPL2025_005,2025-03-26,2025,LSG,PBKS,KL Rahul,108,226,Yes
17,IPL2025_005,2025-03-26,2025,LSG,PBKS,Nicholas Pooran,64,226,No
18,IPL2025_005,2025-03-26,2025,PBKS,LSG,Shikhar Dhawan,77,202,No
19,IPL2025_005,2025-03-26,2025,PBKS,LSG,Liam Livingstone,59,202,No
20,IPL2025_006,2025-03-27,2025,KKR,CSK,Sunil Narine,73,207,No
21,IPL2025_006,2025-03-27,2025,KKR,CSK,Rinku Singh,54,207,No
22,IPL2025_006,2025-03-27,2025,CSK,KKR,Ravindra Jadeja,49,191,No
23,IPL2025_006,2025-03-27,2025,CSK,KKR,MS Dhoni,37,191,No
24,IPL2025_007,2025-03-28,2025,RR,RCB,Jos Buttler,105,224,Yes
25,IPL2025_007,2025-03-28,2025,RR,RCB,Riyan Parag,48,224,No
26,IPL2025_007,2025-03-28,2025,RCB,RR,Faf du Plessis,81,210,No
27,IPL2025_007,2025-03-28,2025,RCB,RR,Glenn Maxwell,56,210,No
28,IPL2025_008,2025-03-29,2025,MI,GT,Ishan Kishan,90,216,No
29,IPL2025_008,2025-03-29,2025,MI,GT,Hardik Pandya,61,216,No
30,IPL2025_008,2025-03-29,2025,GT,MI,Sai Sudharsan,75,201,No
31,IPL2025_008,2025-03-29,2025,GT,MI,Rahul Tewatia,42,201,No
32,IPL2025_009,2025-03-30,2025,DC,SRH,Prithvi Shaw,84,208,No
33,IPL2025_009,2025-03-30,2025,DC,SRH,Axar Patel,39,208,No
34,IPL2025_009,2025-03-30,2025,SRH,DC,Abhishek Sharma,97,203,No
35,IPL2025_009,2025-03-30,2025,SRH,DC,Aiden Markram,46,203,No
36,IPL2025_010,2025-03-31,2025,PBKS,MI,Jitesh Sharma,69,196,No
37,IPL2025_010,2025-03-31,2025,PBKS,MI,Sam Curran,50,196,No
38,IPL2025_010,2025-03-31,2025,MI,PBKS,Tilak Varma,86,202,No
39,IPL2025_010,2025-03-31,2025,MI,PBKS,Tim David,40,202,No
40,IPL2025_011,2025-04-01,2025,CSK,GT,Rachin Ravindra,107,231,Yes
41,IPL2025_011,2025-04-01,2025,CSK,GT,Daryl Mitchell,58,231,No
42,IPL2025_011,2025-04-01,2025,GT,CSK,Wriddhiman Saha,61,199,No
43,IPL2025_011,2025-04-01,2025,GT,CSK,Rashid Khan,29,199,No
44,IPL2025_012,2025-04-02,2025,RCB,LSG,Virat Kohli,94,218,No
45,IPL2025_012,2025-04-02,2025,RCB,LSG,Cameron Green,57,218,No
46,IPL2025_012,2025-04-02,2025,LSG,RCB,Quinton de Kock,81,206,No
47,IPL2025_012,2025-04-02,2025,LSG,RCB,Marcus Stoinis,65,206,No
48,IPL2025_013,2025-04-03,2025,SRH,CSK,Abhishek Sharma,112,239,Yes
49,IPL2025_013,2025-04-03,2025,CSK,SRH,Ruturaj Gaikwad,88,214,No

In [ ]:
df.isnull()

,match_id,match_date,season,team,opponent,player,runs,match_total,century
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False

In [ ]:
import pandas as pd
import numpy as np
student={
    "id":[101,102,103,104,105],"name":["anuu","sujji",np.nan,"sneha","kiran"],
    "department":["BCA","BCA","BSc",np.nan,"BCA"],
    "marks":[85,np.nan,78,92,80]
}
df=pd.DataFrame(student)
print(df)

    id   name department  marks
0  101   anuu        BCA   85.0
1  102  sujji        BCA    NaN
2  103    NaN        BSc   78.0
3  104  sneha        NaN   92.0
4  105  kiran        BCA   80.0

In [ ]:
import pandas as pd
df=pd.read_csv(r"/content/cricket.csv")
df.head()

,match_id,match_date,season,team,opponent,player,runs,match_total,century
0,IPL2025_001,2025-03-22,2025,CSK,MI,Ruturaj Gaikwad,78,198,No
1,IPL2025_001,2025-03-22,2025,CSK,MI,Shivam Dube,45,198,No
2,IPL2025_001,2025-03-22,2025,MI,CSK,Rohit Sharma,66,186,No
3,IPL2025_001,2025-03-22,2025,MI,CSK,Suryakumar Yadav,74,186,No
4,IPL2025_002,2025-03-23,2025,RCB,KKR,Virat Kohli,114,221,Yes

In [ ]:
df[df["player"]=="Virat Kohli"]["team"]

4     RCB
44    RCB
Name: team, dtype: object

In [ ]:
df.sort_values(by=["runs","match_total"],ascending=[False,True])[["player"]].head(1)

        player
4  Virat Kohli

In [ ]:
df.sort_values(by=["runs","match_total"],ascending=[False,True])[["player","runs","match_total"]].head(1)

        player  runs  match_total
4  Virat Kohli   114          221

In [ ]:
df.sort_values(by=["runs","match_total"],ascending=[False,True])[["player","runs","match_total"]].tail(1)

         player  runs  match_total
43  Rashid Khan    29          199

In [ ]:
df.sort_values(by=["runs","match_total"],ascending=[False,True])[["player","runs","match_total","team"]].head(5)

             player  runs  match_total team
4       Virat Kohli   114          221  RCB
48  Abhishek Sharma   112          239  SRH
16         KL Rahul   108          226  LSG
40  Rachin Ravindra   107          231  CSK
24      Jos Buttler   105          224   RR

In [ ]:
df.sort_values(by=["runs","match_total"],ascending=[False,True])[["player","runs","match_total","team"]].tail(5)

           player  runs  match_total team
31  Rahul Tewatia    42          201   GT
39      Tim David    40          202   MI
33     Axar Patel    39          208   DC
23       MS Dhoni    37          191  CSK
43    Rashid Khan    29          199   GT

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   match_id     50 non-null     object
 1   match_date   50 non-null     object
 2   season       50 non-null     int64
 3   team         50 non-null     object
 4   opponent     50 non-null     object
 5   player       50 non-null     object
 6   runs         50 non-null     int64
 7   match_total  50 non-null     int64
 8   century      50 non-null     object
dtypes: int64(3), object(6)
memory usage: 3.6+ KB

In [ ]:
df["runs"].mean()

np.float64(69.7)

In [ ]:
avg_runs=df["runs"].mean()
print(int(avg))

69

In [ ]:
df["runs"].fillna(int(df["runs"].mean()))

0      78
1      45
2      66
3      74
4     114
5      43
6      71
7      58
8     103
9      68
10     91
11     55
12     96
13     47
14     82
15     52
16    108
17     64
18     77
19     59
20     73
21     54
22     49
23     37
24    105
25     48
26     81
27     56
28     90
29     61
30     75
31     42
32     84
33     39
34     97
35     46
36     69
37     50
38     86
39     40
40    107
41     58
42     61
43     29
44     94
45     57
46     81
47     65
48    112
49     88
Name: runs, dtype: int64

In [ ]:
df["Wickets"]=df["Wickets"].fillna(int(df["Wickets"].mean()))

In [ ]:
df.head(2)

,match_id,match_date,season,team,opponent,Wickets,player,runs,match_total,century
0,IPL2025_001,2025-03-22,2025,CSK,MI,2,Ruturaj Gaikwad,78,198,No
1,IPL2025_001,2025-03-22,2025,CSK,MI,3,Shivam Dube,45,198,No

In [ ]:
df.columns

Index(['match_id', 'match_date', 'season', 'team', 'opponent', 'Wickets',
       'player', 'runs', 'match_total', 'century'],
      dtype='object')

In [ ]:
df[df["team"]=="RCB"]["player"]

4        Virat Kohli
5      Rajat Patidar
26    Faf du Plessis
27     Glenn Maxwell
44       Virat Kohli
45     Cameron Green
Name: player, dtype: object

In [ ]:
df[df["runs"]>70]["player"]

0      Ruturaj Gaikwad
3     Suryakumar Yadav
4          Virat Kohli
6         Shreyas Iyer
8          Travis Head
10    Yashasvi Jaiswal
12        Shubman Gill
14        Rishabh Pant
16            KL Rahul
18      Shikhar Dhawan
20        Sunil Narine
24         Jos Buttler
26      Faf du Plessis
28        Ishan Kishan
30       Sai Sudharsan
32        Prithvi Shaw
34     Abhishek Sharma
38         Tilak Varma
40     Rachin Ravindra
44         Virat Kohli
46     Quinton de Kock
48     Abhishek Sharma
49     Ruturaj Gaikwad
Name: player, dtype: object

In [ ]:
df[df["runs"]>50][["player","runs"]]

              player  runs
0    Ruturaj Gaikwad    78
2       Rohit Sharma    66
3   Suryakumar Yadav    74
4        Virat Kohli   114
6       Shreyas Iyer    71
7      Andre Russell    58
8        Travis Head   103
9   Heinrich Klaasen    68
10  Yashasvi Jaiswal    91
11      Sanju Samson    55
12      Shubman Gill    96
14      Rishabh Pant    82
15      David Warner    52
16          KL Rahul   108
17   Nicholas Pooran    64
18    Shikhar Dhawan    77
19  Liam Livingstone    59
20      Sunil Narine    73
21       Rinku Singh    54
24       Jos Buttler   105
26    Faf du Plessis    81
27     Glenn Maxwell    56
28      Ishan Kishan    90
29     Hardik Pandya    61
30     Sai Sudharsan    75
32      Prithvi Shaw    84
34   Abhishek Sharma    97
36     Jitesh Sharma    69
38       Tilak Varma    86
40   Rachin Ravindra   107
41    Daryl Mitchell    58
42   Wriddhiman Saha    61
44       Virat Kohli    94
45     Cameron Green    57
46   Quinton de Kock    81
47    Marcus Stoinis    65
48   Abhishek Sharma   112
49   Ruturaj Gaikwad    88